# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7bf6bc93ec5095eb28d1e4962b922eb7ff98e3a5ade7274d4ccd4f0c09305d309f3bb43aae65e179554add589b8258b38b5da03053abcbd50d969a1fc27f6961

test:
  secret_key_base: 0127d68c72bcf19c8d3a8febf8e8f9b9369bc79f97ae06ea8d55cbdf1bc571027b8cc550005da02ee573d5a8d3040ca402c6a598489d3e19e156403adccff4fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
